FROM node:18-alpine

WORKDIR /src

COPY package*.json ./

RUN npm install -g nodemon

RUN npm install

COPY . .

EXPOSE 5001

ENTRYPOINT [ "nodemon","backend/sdr_simulation.js" ]
CMD ["npm", "run", "dev"]
