version: '3.8'
services:
  web:
    build: .
    ports:
      - "6001:6000"
    volumes:
      - .:/src
    environment:
      - NODE_ENV=production
    command: node src/server.js

  sdr:
    build:
      context: .
      dockerfile: Dockerfile.sdr
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/src
    command: node src/sdr_simulation.js

  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydb
  #   ports:
  #     - "5432:5432"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/src
    command: npm start
