FROM node:18 AS builder

WORKDIR /app

COPY ./package*.json ./

RUN npm ci

COPY . .

# EXPOSE 3000

# CMD ["npm", "start"]

RUN npm run build

from node:18-alpine

WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/frontend/.next ./frontend/.next
COPY --from=builder /app/.env .env
# COPY --from=builder /app/public ./public

RUN npm ci --only=production

EXPOSE 3000

CMD ["npm", "run", "start"]
