CREATE TABLE "Devices" (
  "d_id" integer PRIMARY KEY,
  "d_address" inet NOT NULL,
  "d_port" integer NOT NULL
);

CREATE TABLE "Channels" (
  "c_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "d_id" integer NOT NULL,
  "c_name" varchar NOT NULL,
  "c_freq" integer NOT NULL,
  "c_endpoint" integer
);

CREATE TABLE "Utilisation" (
  "u_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "c_id" integer NOT NULL,
  "a_start_time" integer NOT NULL,
  "a_end_time" integer,
  "duration" integer,
  "is_active" bool DEFAULT false
);

CREATE TABLE "Strength" (
  "s_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "c_id" integer NOT NULL,
  "s_sample_time" integer NOT NULL,
  "s_strength" float NOT NULL
);

CREATE TABLE "Sessions" (
  "session_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "auth_token" varchar NOT NULL
);

CREATE TABLE "Session_Listeners" (
  "session_id" integer,
  "c_id" integer,
  PRIMARY KEY ("session_id", "c_id")
);

COMMENT ON COLUMN "Devices"."d_id" IS 'Unique preallocated random id identifying a specific raspberry pi';

COMMENT ON COLUMN "Devices"."d_address" IS 'Current Public IP address for this raspberry pi';

COMMENT ON COLUMN "Devices"."d_port" IS 'Current Port for accessing this raspberry pi';

COMMENT ON COLUMN "Channels"."c_id" IS 'unique channel ID (combines name and frequency)';

COMMENT ON COLUMN "Channels"."c_name" IS 'DFES Channel name';

COMMENT ON COLUMN "Channels"."c_freq" IS 'DFES Channel frequency';

COMMENT ON COLUMN "Channels"."c_endpoint" IS 'Unique random integer, which acts as the HTTP endpoint for streaming';

COMMENT ON COLUMN "Utilisation"."a_start_time" IS 'Start time for a period where channel was used/was being monitored';

COMMENT ON COLUMN "Utilisation"."a_end_time" IS 'End time for a period where channel was used, if null assume ongoing';

COMMENT ON COLUMN "Utilisation"."duration" IS 'For ease of use, =end_time-start_time';

COMMENT ON COLUMN "Utilisation"."is_active" IS 'True=no data because channel was being monitored';

COMMENT ON COLUMN "Strength"."s_sample_time" IS 'Epoch time (seconds) this strength sample was taken';

COMMENT ON COLUMN "Strength"."s_strength" IS 'Measured in Dbm';

COMMENT ON COLUMN "Sessions"."session_id" IS 'identifies a client session to track ongoing monitoring';

COMMENT ON COLUMN "Sessions"."auth_token" IS 'Entra-ID token for verification - Not sure if necessary';

ALTER TABLE "Channels" ADD FOREIGN KEY ("d_id") REFERENCES "Devices" ("d_id");

ALTER TABLE "Utilisation" ADD FOREIGN KEY ("c_id") REFERENCES "Channels" ("c_id");

ALTER TABLE "Strength" ADD FOREIGN KEY ("c_id") REFERENCES "Channels" ("c_id");

ALTER TABLE "Session_Listeners" ADD FOREIGN KEY ("session_id") REFERENCES "Sessions" ("session_id");

ALTER TABLE "Session_Listeners" ADD FOREIGN KEY ("c_id") REFERENCES "Channels" ("c_id");
