name: Build and deploy Dockerized CITS3200 App

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker images
      - name: Build and push web image
        run: |
          docker build --platform linux/amd64 -t yelaoshi/web:latest -f Dockerfile.web .
          docker push yelaoshi/web:latest

      - name: Build and push frontend image
        run: |
          docker build --platform linux/amd64 -t yelaoshi/frontend:latest -f Dockerfile.frontend .
          docker push yelaoshi/frontend:latest

      - name: Build and push db image
        run: |
          docker build --platform linux/amd64 -t yelaoshi/db:latest -f Dockerfile.db .
          docker push yelaoshi/db:latest

      - name: Build and push nginx image
        run: |
          docker build --platform linux/amd64 -t yelaoshi/nginx:latest -f Dockerfile.nginx .
          docker push yelaoshi/nginx:latest
