name: Build and deploy Dockerized Node.js app to Azure Web App - cits32005as

on:
  push:
    branches:
      - deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to DockerHub or Azure Container Registry (ACR)
      # You need to set up DockerHub credentials in your repository secrets
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker images for web, frontend, and db
      - name: Build Docker Compose services
        run: docker-compose -f docker-compose.yml build

      # Push Docker images to DockerHub (or ACR if using Azure Container Registry)
      - name: Push Docker images to DockerHub
        run: docker-compose -f docker-compose.yml push

      # Deploy the Docker Compose setup to Azure
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Download the Docker images from DockerHub (Azure will pull them as part of deployment)
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Deploy Docker containers to Azure Web App for Containers
      - name: 'Deploy to Azure Web App for Containers'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cits32005as'
          images: |
            web: yourdockerhubusername/web:latest
            frontend: yourdockerhubusername/frontend:latest
            db: yourdockerhubusername/db:latest
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_59C98818EF8C463A80B184D72D1ED767 }}

